name: 'Matrix Lock'
description: 'Locking mechanism for Matrices'

inputs:
  step:
    description: 'init | wait | continue'
    required: true
  order:
    description: 'the order for the whole process | required for the init step'
    required: false
  id:
    description: 'the identifier of which it should wait and act | required for the init continue'
    required: false
  retry-count:
    description: 'the count of how many times we wait for the lock'
    default: 6
  retry-delay:
    description: 'the delay in seconds before retrying'
    default: 10

runs:
  using: 'node20'
  main: 'dist/index.js'
